# Configure the encoder/decoder for actual compression/decompression 
#配置3D点云数据的编解码器，以及数据的平移和缩放参数
# Codec class
codec: 'grasp_codec'

# Native translation and scaling of the data
translate: [131072, 131072, 131072]
scale: 1
