# 版权所有 (c) 2010-2022，InterDigital
# 保留所有权利。

# 请参阅根文件夹下的LICENSE。

# 配置ModelNet数据集以加载为稀疏体素

# 数据集的常见选项
dataset: modelnet_simple  # 数据集的名称为 'modelnet_simple'
num_points: 20000  # 点云的数量为20000
coord_min: 0  # 坐标的最小值为0
coord_max: 511  # 坐标的最大值为511
voxelize: True  # 将数据体素化
sparse_collate: True  # 使用稀疏的整理方式
centralize: True  # 将数据集中化

# 各个配置下的选项
train_cfg:
    batch_size: 8  # 训练集的批处理大小为8
    shuffle: True  # 对训练集进行洗牌
    num_workers: 4  # 使用4个工作进程加载数据
    augmentation: True  # 对训练集进行数据增强
    split: train  # 这是训练集的配置
val_cfg:
    batch_size: 8  # 验证集的批处理大小为8
    shuffle: False  # 不对验证集进行洗牌
    num_workers: 1  # 使用1个工作进程加载数据
    augmentation: False  # 不对验证集进行数据增强
    split: val  # 这是验证集的配置
test_cfg:
    batch_size: 1  # 测试集的批处理大小为1
    num_points: null  # 测试集的点云数量为null，表示使用默认值
    shuffle: False  # 不对测试集进行洗牌
    num_workers: 1  # 使用1个工作进程加载数据
    augmentation: False  # 不对测试集进行数据增强
    split: test  # 这是测试集的配置
